baseURL = "https://devbackend.com/"
languageCode = "en-us"
title = "Backend engineer Ivan Krivonos"
theme = "hugo-resume"

[params]
    firstName = "Ivan"
    lastName = "Krivonos"
    address = "Moscow"
    phone = "+7-914-976-5239"
    contactNote = "Backend engineer"
    profileImage = "img/pic.jpeg"
    email = "devbackend@yandex.ru"
    description = "Backend developer: PHP/Golang; author of telegram channel @devbackend"
    favicon = "img/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = false

    showQr = false

[[params.handles]]
    name = "Telegram"
    link = "https://telegram.me/devbackend"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/devbackend"

[[params.handles]]
    name = "VK"
    link = "http://vk.com/ivan.krivonos"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/devbackend/"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/ivan.krivonos"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/ivan_krivonos"

[[params.handles]]
    name = "Instagram"
    link = "https://www.instagram.com/ivan.krivonos/"    
